version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/codedeploy_vhost
hooks:
  # BeforeInstall:
  #   - location: script/install_dependencies.sh
  #     timeout: 300
  #     runas: root
  AfterInstall:
    - location: scripts/create_vhost.sh
      timeout: 300
      runas: root
  Install:
    - location: scripts/active_vhost.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/after_active.sh
      timeout: 300
      runas: root
  # ApplicationStop:
  #   - location: script/stop_server.sh
  #     timeout: 300
  #     runas: root
